<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/fontawesome.js"></script>
<script src="assets/js/owl.carousel.min.js"></script>
<script src="unpkg.com/aos%403.0.0-beta.6/dist/aos.js"></script>
<script src="assets/js/jquery.magnific-popup.min.js"></script>
<script src="cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
<script src="cdn.jsdelivr.net/npm/%40popperjs/core%402.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="assets/js/slick-slider.js"></script>
<script src="assets/js/mobile-menu.js"></script>
<script src="assets/js/tilt.jquery.js"></script>
<script src="assets/js/jquery.countup.js"></script>
<script src="assets/js/jquery.nice-select.js"></script>
<script src="assets/js/jquery.lineProgressbar.js"></script>
<script src="assets/js/mobile-meanmenu.js"></script>
<script src="assets/js/modal-video.min.js"></script>
<script src="assets/js/main.js"></script>